name: Artifact Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Step (Create file)
      run: |
        mkdir output
        echo "This is a sample build artifact" > output/result.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-result
        path: output/
        retention-days: 7
