name: Hardcoded Secret Demo

on:
  push:
    branches: [ main ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Show hardcoded secret
        run: |
          echo "The secret key is: ThisIsMyFakeSecret123"
