name: Demo Secrets Workflow

on:
  push:
    branches: [ main ]

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python script using secret
        run: |
          echo "Running script..."
          echo "MY_SECRET is: ${{ secrets.MY_SECRET }}"
